# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RighteousRevenue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Charts'
pod 'SQLite.swift'
pod 'TextFieldEffects'
pod 'BEMCheckBox'
pod 'YouTubePlayer'
pod 'NVActivityIndicatorView'
pod 'SwiftTheme'
pod 'SwiftyStoreKit'
pod 'SCLAlertView'
pod 'iOSDropDown'
pod 'Google-Mobile-Ads-SDK'

  # Pods for RighteousRevenue

  target 'RighteousRevenueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RighteousRevenueUITests' do
    # Pods for testing
  end

end
