# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RighteousRevenue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Charts'
pod 'SideMenu'
pod 'SQLite.swift'

  # Pods for RighteousRevenue

  target 'RighteousRevenueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RighteousRevenueUITests' do
    # Pods for testing
  end

end
